obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT3267) += Config_FT6X36.o DetailThreshold.o Global.o ini.o Test_FT6X36.o test_lib.o




#obj-y         += Config_FT6X36.o
#obj-y         += DetailThreshold.o
#obj-y         += Global.o
#obj-y         += ini.o
#obj-y         += Test_FT6X36.o
#obj-y         += test_lib.o
